version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
#    environment:
#      - MB_DB_FILE=/metabase-data/metabase.db
#      - MB_DB_TYPE=mysql
#      - MB_DB_HOST=givtu-stage-sydney-database.coyeaggqwolq.ap-southeast-2.rds.amazonaws.com
#      - MB_DB_PORT=3306
#      - MB_DB_USER=admin
#      - MB_DB_PASS=terraformdb123
#      - MB_DB_NAME=givtudevsydney
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-data:
    driver: local

